version: "3.9"

services:
  botjuris-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: botjuris-app
    restart: always
    env_file:
      - ./.env
    environment:
      REDIS_URL: "redis://default:1234567890@redis:6379/0"
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: botjuris-redis
    restart: always
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "1234567890"]
    ports:
      - "6379:6379"

